#!/bin/sh

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <queue_size> <num_workers> <document_root> <log_file>"
    exit
fi

echo "Launching srvwww..."
CLASSPATH=classes:classes/amqp-client-5.21.0.jar:classes/slf4j-api-1.7.2.jar:classes/slf4j-simple-1.7.2.jar
java -cp $CLASSPATH srvwww.SrvWWW $1 $2 $3 $4 &
