#!/bin/sh

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <client_id> <requests_file> <downloads_directory> <max_chunk_size>"
    exit
fi

echo "Launching Client..."
CLASSPATH=classes:classes/amqp-client-5.21.0.jar:classes/slf4j-api-1.7.2.jar:classes/slf4j-simple-1.7.2.jar
java -cp $CLASSPATH client.Client $1 $2 "$PWD/$3" $4